name: Build

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  win64:
    runs-on: windows-2019
    env:
      CMAKE_GENERATOR: "Visual Studio 16 2019"
      CMAKE_SYSTEM_VERSION: "10.0.18363.657"
      WINDOWS_DEPS_VERSION: '2019'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: obsproject/obs-studio
          path: obs-studio
          ref: 27.2.3
      - uses: actions/checkout@v2
        with:
          repository: e00e/obs-amf
          path: obs-studio/plugins/amftest
      # Overwrite the whole file because we are not building any other plugin.
      - run: Set-Content -Path 'obs-studio/plugins/CMakeLists.txt' -Value 'add_subdirectory(amftest)'

      # The following is mostly taken from obs-studio's workflow definition.

      - uses: microsoft/setup-msbuild@v1
      - name: Download dependencies
        run: |
          curl -kLO https://cdn-fastly.obsproject.com/downloads/dependencies${{ env.WINDOWS_DEPS_VERSION }}.zip -f --retry 5 -C -
          7z x dependencies${{ env.WINDOWS_DEPS_VERSION }}.zip -o"${{ github.workspace }}/cmbuild/deps"
      - name: Configure
        run: |
          mkdir build64
          cd build64
          cmake -G"${{ env.CMAKE_GENERATOR }}" -A"x64" -DCMAKE_SYSTEM_VERSION="${{ env.CMAKE_SYSTEM_VERSION }}" -DDepsPath="${{ github.workspace }}/cmbuild/deps/win64" -DCOPIED_DEPENDENCIES=FALSE -DCOPY_DEPENDENCIES=TRUE -DDISABLE_UI=TRUE ../obs-studio
      - name: Build
        run: msbuild /m /p:Configuration=RelWithDebInfo build64/plugins/amftest/amftest.sln
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: win64
          path: build64/plugins/amftest/RelWithDebInfo/amftest.dll
